Add 14th homework
lizxqws/JS-homework pull request #15
Opened 2024-05-31 09:17 UTC by lizxqws

2024-06-10 15:05 UTC, marianaD4 requested changes

2024-06-17 19:22 UTC, lizxqws commented on index.js
> +  users.filter(user => user.gender === gender).map(user => user.name);
якщо зробити тільки за допомогою одного map (без filter), в кінцевому масиві буде undefined, якщо user.gender !== gender

2024-06-25 14:24 UTC, marianaD4 requested changes

2024-06-25 14:24 UTC, marianaD4 commented on index.js
> +  const filterdUsersNames = [];
Не потрібно створювати новий масив вручну,  метод map сам його створить

2024-09-12 14:28 UTC, marianaD4 approved these changes

2024-09-14 12:50 UTC, closed without merging